### ISSUE TITLE
Add full name field for sign up form

### ISSUE THREAD

**Issue by xandrck** [xandrck/oblivion#34]
Add full name field to user's regisrtration form

**Comment by GeckVel** [comment]
Done, but doesn't create new user on db

**Comment by xandrck** [comment]
I guess you forgot to add pull requests, can you add it please? :)
